export type NewsType = {
    article_id: String,
    title: String | null,
    link: String | null,
    keywords: any,
    creator: String[] |null,
    video_url: null,
    description: String | null,
    content: String | null,
    pubDate: String | null,
    pubDateTZ: String | null,
    image_url: String | null,
    source_id: String | null,
    source_priority: String | number,
    source_name: String | null,
    source_url: String | null,
    source_icon: String | null,
    language: String | null,
    country: any,
    category:  String[],
    ai_tag: String | null,
    sentiment: String | null,
    sentiment_stats: String | null,
    ai_region: String | null,
    ai_org: String | null,
    duplicate: Boolean
}