
export const ChatBotStyles = {
	// styles
	tooltipStyle: {},
	notificationBadgeStyle: {},
	chatWindowStyle: {},
	headerStyle: {},
	bodyStyle: { background:"#0a0a0a"},
	chatInputContainerStyle: { background:"#0a0a0a"},
	chatInputAreaStyle: {background:"#0a0a0a",color:"white" },
	chatInputAreaFocusedStyle: {background:"#0a0a0a",color:"white"},
	chatInputAreaDisabledStyle: {background:"#0a0a0a",color:"white"},
	userBubbleStyle: {},
	botBubbleStyle: {},
	botOptionStyle: {},
	botOptionHoveredStyle: {},
	botCheckboxRowStyle: {},
	botCheckboxNextStyle: {},
	botCheckMarkStyle: {},
	botCheckMarkSelectedStyle: {},
	characterLimitStyle: {},
	characterLimitReachedStyle: {},
	chatHistoryLineBreakStyle: {},
	chatMessagePromptStyle: {},
	chatMessagePromptHoveredStyle: {},
	footerStyle: {background:"#0a0a0a",color:"white"},
	loadingSpinnerStyle: {},
	mediaDisplayContainerStyle: {},
	chatButtonStyle: {},
	chatButtonHoveredStyle: {},
	chatHistoryButtonStyle: {},
	chatHistoryButtonHoveredStyle: {},
	sendButtonStyle: {},
	sendButtonHoveredStyle: {},
	sendButtonDisabledStyle: {},
	audioButtonStyle: {},
	audioButtonDisabledStyle: {},
	closeChatButtonStyle: {},
	emojiButtonStyle: {},
	emojiButtonDisabledStyle: {},
	fileAttachmentButtonStyle: {},
	fileAttachmentButtonDisabledStyle: {},
	notificationButtonStyle: {},
	notificationButtonDisabledStyle: {},
	voiceButtonStyle: {},
	voiceButtonDisabledStyle: {},
	chatIconStyle: {},
	audioIconStyle: {},
	audioIconDisabledStyle: {},
	closeChatIconStyle: {},
	emojiIconStyle: {},
	emojiIconDisabledStyle: {},
	fileAttachmentIconStyle: {},
	fileAttachmentIconDisabledStyle: {},
	notificationIconStyle: {},
	notificationIconDisabledStyle: {},
	voiceIconStyle: {},
	voiceIconDisabledStyle: {},
	sendIconStyle: {},
	sendIconDisabledStyle: {},
	sendIconHoveredStyle: {},
	rcbTypingIndicatorContainerStyle: {},
	rcbTypingIndicatorDotStyle: {},
	toastPromptContainerStyle: {},
	toastPromptStyle: {},
	toastPromptHoveredStyle: {}
}
export default ChatBotStyles;